baseURL = "https://schulichignite.com/"
languageCode = "en-us"
title = "Schulich Ignite"
summaryLength = 20
relativeURLs = true

[params]
    email = "info@schulichignite.com"
    # status = "closed" # When no recruitment is happening, and mailing list is available
    # status = "signup"     # When recruitment is happening
    status = "live"        # When courses are live
    emailListSignup = "https://forms.gle/ZJoDAbcTf1M3NBxYA"
    mentorSignUp = ""
    menteeSignUp = ""
    ignitePoints = "https://docs.google.com/spreadsheets/d/1YwXV-09PoVZI0_yPvmnEHCQpg4NaA2JGvyP-xfdyBCM/edit?usp=sharing"
    sparkDocs    = "https://spark.schulichignite.com/"
    submitBugBusters   = "https://docs.google.com/forms/d/e/1FAIpQLScwCd0u3Tcw8lxQTGhiU5DROfqKgBPkfrhVEKXdn9O-D7K6mg/viewform?usp=sf_link"
    submitPythonicLava = "https://docs.google.com/forms/d/e/1FAIpQLSf7CEqEWACdKhn-rZape329ySsR3Zo5oBSdFEgvWxIYNI8ViQ/viewform?usp=sf_link"
    submitScorch = "https://docs.google.com/forms/d/e/1FAIpQLSdjPwp-zFQCVFON7PWfL1jtCqcTds2yc9EmaqZdjowjKSQ-rA/viewform?usp=sf_link" 
    submitFlare = "https://docs.google.com/forms/d/e/1FAIpQLSf17M81kmL-Y2pt5FDxsgHDOt3St299b30ft0oTdMcxa9iVSw/viewform?usp=sf_link"
    current_startDate = 2024-02-18T14:15:59-06:00
    current_endDate   = 2024-04-20T14:15:59-06:00
    [params.links]
        youtube = "https://www.youtube.com/channel/UC7tNvdbu952HOUl_4nK7iww"
        instagram = "https://www.instagram.com/schulichignite"
        facebook = "https://www.facebook.com/SchulichIgnite/"
        linkedin = "https://linkedin.com/company/schulich-ignite/"
        discord = "https://discord.gg/F3Qjqqj"
        tiktok  = "https://vm.tiktok.com/ZSHPbWU3/"

[markup.goldmark.tableOfContents]
endLevel = 4 # End on H4's

[markup.goldmark.extensions]
footnote = true

[markup.goldmark.renderer]
    unsafe= true

[taxonomies]
  author = "authors"
  tag = "tags"
  difficulty = "difficulty"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
